# Generated by Django 4.0.3 on 2023-07-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=120)),
                ('image', models.ImageField(max_length=120, upload_to='upload/product_image')),
            ],
        ),
    ]
