# Generated by Django 4.0.3 on 2023-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
