# Generated by Django 4.0.3 on 2023-07-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
